/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllDiscussion: typeof import('./src/components/all-discussion/all-discussion.vue')['default']
    CelebrityDetail: typeof import('./src/components/celebrity-detail copy/celebrity-detail.vue')['default']
    CelebrityInfo: typeof import('./src/components/celebrity-info/celebrity-info.vue')['default']
    CelebrityList: typeof import('./src/components/celebrity-list/celebrity-list.vue')['default']
    CelebrityWorks: typeof import('./src/components/celebrity-works/celebrity-works.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    MovieComment: typeof import('./src/components/movie-comment/movie-comment.vue')['default']
    MovieDetail: typeof import('./src/components/movie-detail/movie-detail.vue')['default']
    MovieInfo: typeof import('./src/components/movie-info/movie-info.vue')['default']
    MovieList: typeof import('./src/components/movie-list/movie-list.vue')['default']
    MovieReview: typeof import('./src/components/movie-review/movie-review.vue')['default']
    MovieShow: typeof import('./src/components/movie-show/movie-show.vue')['default']
    Rank: typeof import('./src/components/rank/rank.vue')['default']
    RankDetail: typeof import('./src/components/rank-detail/rank-detail.vue')['default']
    RankList: typeof import('./src/components/rank-list/rank-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/search.vue')['default']
    Suggest: typeof import('./src/components/suggest/suggest.vue')['default']
    Tab: typeof import('./src/components/tab/tab.vue')['default']
    UserCenter: typeof import('./src/components/user-center/user-center.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
